ViewModels/GroupViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Mng.Models;

namespace Mng.ViewModels
{
    public class GroupViewModel
    {
        /*
        public int Id { get; set; }

        [Required(ErrorMessage = "Название группы не может быть пустым")]
        [DisplayName("Название")]
        [StringLength(160)]
        public string Title { get; set; }*/

        public Group groupField { get; set; }
        public List<AppUser> AppUsers { get; set; }
        public bool[] MngWrk { get; set; }
    }
}

Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mng.Data;
using Mng.Models;
using Microsoft.AspNetCore.Identity;
using Mng.ViewModels;

using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Mng.Controllers
{
    [Authorize(Roles = "Worker,Admin")]
    public class GroupsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly IAuthorizationService _authorizationService;
        public GroupsController(ApplicationDbContext context,UserManager<AppUser> userManager, IAuthorizationService AuthServ)
        {
            _authorizationService = AuthServ;
            _context = context;
            _userManager = userManager;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {

            return View(await _context.Groups.ToListAsync());
        }

        public async Task<IActionResult> UserSearch(string searchString,int groupid,string currentFilter,int? pageNumber)
        {

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            ViewBag.groupid = groupid;

            var @group = _context.Groups.Include(g => g.GroupMembers).FirstOrDefault(g => g.Id == groupid);

            if (!await GroupAccessAsync(@group)) return NotFound();

            if (!String.IsNullOrEmpty(searchString) && @group != null)
            {
                var users = _context.Users
                    .AsEnumerable()
                    .Where(u => u.Email!="Admin@email.com" && u.Email.Contains(searchString) && @group.GroupMembers.FirstOrDefault(gm => gm.AppUserId == u.Id) == null);

                int pageSize = 3;
                return View("Search",await PaginatedList<AppUser>.CreateAsync(users.AsQueryable<AppUser>(), pageNumber ?? 1, pageSize));

            }

            return View("Search", new List<AppUser>());
        }
        public async Task<IActionResult> Promote(string userid,int groupid, string position)
        {
            
            var @group = _context.Groups.Include(g => g.GroupMembers).FirstOrDefault(g => g.Id == groupid);

            if (!await GroupAccessAsync(@group)) return NotFound();

            var user = _context.Users.FirstOrDefault(u => u.Id == userid);
            if (@group!= null && user != null)
            {
                await _userManager.AddToRoleAsync(user, "Worker");
                @group.GroupMembers.Add(new GroupMember() { AppUserId = userid, GroupId = groupid, Position = position });
                
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction("UserSearch", new { searchString = "", groupid = groupid });
            }
            return RedirectToAction("Details", new { id = groupid });
            return RedirectToAction("UserSearch",new { searchString="",groupid = groupid });
        }
       
        // GET: Groups/Details/5

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var @group = await _context.Groups.Include(g =>g.Mangas).Include(g => g.GroupMembers)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (!await GroupAccessAsync(@group)) return NotFound();

            bool[] tmp = new bool[@group.GroupMembers.Count];
            int count = 0;
            List<AppUser> usersList = new List<AppUser>();

            foreach (var v in @group.GroupMembers)
            {
                if (v.Position=="Manager")
                {
                    tmp[count] = true;
                }
                else tmp[count] = false;
                usersList.Add(_context.Users.FirstOrDefault(u => u.Id == v.AppUserId));
                count++;
            }
            GroupViewModel GVM = new GroupViewModel();
            GVM.groupField = @group;
            GVM.MngWrk = tmp;
            GVM.AppUsers = usersList;
            return View(GVM);
        }
        public async Task<IActionResult> Demote(string userid,int groupid)
        {
            var @group = await _context.Groups.Include(g => g.GroupMembers)
                .FirstOrDefaultAsync(m => m.Id == groupid);

            if (!await GroupAccessAsync(@group)) return NotFound();

            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == userid);

            if (user != null)
            {
                GroupMember GM = @group.GroupMembers.FirstOrDefault(gm=>gm.AppUserId == userid && gm.GroupId == groupid); 
                @group.GroupMembers.Remove(GM);
                
                if (await _userManager.IsInRoleAsync(user, "Worker"))
                {
                    await _userManager.RemoveFromRoleAsync(user, "Worker");
                }
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Details", new { id = groupid });
        }
        // GET: Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="Admin")]
        public async Task<IActionResult> Create([Bind("Id,Title")] Group @group)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);

            if (!await GroupAccessAsync(@group)) return NotFound();

            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] Group @group)
        {
            if (id != @group.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.Id == id);

            if (!await GroupAccessAsync(@group)) return NotFound();

            return View(@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.Include(g => g.Mangas).FirstOrDefaultAsync(g => g.Id == id);

            if (!await GroupAccessAsync(@group)) return NotFound();

            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.Id == id);
        }
        [NonAction]
        private async Task<bool> GroupAccessAsync(Group @group)
        {
            if (@group == null)
            {
                return false;
            }

Controllers/MangasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mng.Data;
using Mng.Models;
using System.Web;

using Microsoft.AspNetCore.Authorization;

namespace Mng.Controllers
{
    [Authorize(Roles = "Worker,Admin")]
    public class MangasController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IAuthorizationService _authorizationService;
        public MangasController(ApplicationDbContext context, IAuthorizationService AuthServ)
        {
            _context = context;
            _authorizationService =  AuthServ;
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Mangas.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Mangas.Include(p=>p.Parts)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (!await GroupAccessAsync(manga)) return NotFound();
            
            return View(manga);
        }
        public async Task<IActionResult> Create(int? groupid)
        {
            if(!(await _authorizationService.AuthorizeAsync(User, _context.Groups.FirstOrDefault(g => g.Id == groupid), "GroupMember")).Succeeded)
                return NotFound();

            ViewBag.groupid = groupid;
            return View();
        }

        // POST: Mangas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Desc,Price,Genre,Count,PriceStart,GroupId")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manga);
                
                if (!await GroupAccessAsync(manga)) return NotFound();

                
                await _context.SaveChangesAsync();
                return RedirectToAction("Details","Groups",new { id = manga.GroupId});
            }
            return View(manga);
        }

        // GET: Mangas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Mangas.FindAsync(id);

            if (!await GroupAccessAsync(manga)) return NotFound();

            return View(manga);
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Desc,Price,Genre,Count,PriceStart,GroupId")] Manga manga)
        {
            if (id != manga.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (!await GroupAccessAsync(manga)) return NotFound();
                try
                {
                    _context.Update(manga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MangaExists(manga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details","Groups", new { id = manga.GroupId});
            }
            return View("Index", "Groups");
        }

        // GET: Mangas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Mangas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (!await GroupAccessAsync(manga)) return NotFound();

            return View(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manga = await _context.Mangas.FindAsync(id);

            if (!await GroupAccessAsync(manga)) return NotFound();

            _context.Mangas.Remove(manga);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Groups", new { id = manga.GroupId });
        }

        private bool MangaExists(int id)
        {
            return _context.Mangas.Any(e => e.Id == id);
        }

        [NonAction]
        private async Task<bool> GroupAccessAsync(Manga manga)
        {
            if (manga == null) 
                return false;

            _context.Mangas.Include(m => m == manga);
            
            _context.Entry(manga).Reference(m => m.Group).Load();
            var @group = manga.Group;
            if (@group == null)
            {
                return false;
            }
            var authorizationResult = await _authorizationService
                    .AuthorizeAsync(User, @group, "GroupMember");

            return authorizationResult.Succeeded;
        }
    }
}

Views/Groups/Create.cshtml
@model Mng.Models.Group

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Groups/Delete.cshtml
@model Mng.Models.Group

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Groups/Details.cshtml
@model Mng.ViewModels.GroupViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.groupField.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.groupField.Title)
        </dd>
    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Название главы
            </th>
            <th>
                Описание
            </th>
            <th>
                Страниц в главе
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.groupField.Mangas)
        {
            <tr>
                <td>
                    <a asp-controller="Mangas" asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Count)
                </td>
                <td>
                    <a asp-controller="Mangas" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Mangas" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<a asp-controller="Mangas" asp-action="Create" asp-route-groupid="@Model.groupField.Id">Create new manga</a>

@if (Context.User.IsInRole("Admin"))
{
    int count = 0;

    <p>
        <form asp-controller="Groups" asp-action="UserSearch">
            User Email: <input type="text" name="searchString" />
            <input type="hidden" name="groupid" value="@Model.groupField.Id" />
            <input type="submit" value="Find" />
        </form>

    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Пользователь
                </th>
                <th>
                    Мэнэджер
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            
            

            @foreach (var item in Model.AppUsers)
            {
                <tr>
                   
                    <td>
                        @item.Email 
                    </td>
                    <td>
                        @if (Model.MngWrk[count]) 
                            {<span> Manager</span>}
                        else
                            {
                                <span> Worker</span>
                            }
                    </td>
                    <td>
                        <a asp-controller="Groups" asp-action="Demote" asp-route-groupid="@Model.groupField.Id" asp-route-userid="@item.Id">Demote</a>
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>




}



<div>
    <a asp-action="Edit" asp-route-id="@Model.groupField.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Groups/Edit.cshtml
@model Mng.Models.Group

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Groups/Index.cshtml
@model IEnumerable<Mng.Models.Group>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>

                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>

                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Groups/Search.cshtml
@model PaginatedList<Mng.Models.AppUser>
@{
    ViewData["Title"] = "Index";
}

@if (Context.User.IsInRole("Admin"))
{

    <p>
        <form asp-controller="Groups" asp-action="UserSearch">
            User Email: <input type="text" name="searchString" />

            <input type="hidden" name="groupid" value="@ViewBag.groupid" />
            <input type="submit" value="Find" />
        </form>

    </p>




    <h1>Search</h1>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model[0].Email)
                </th>

                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>

                        @Html.DisplayFor(modelItem => item.Email)

                    </td>
                    <td>
                        <a asp-controller="Groups" asp-action="Promote" asp-route-userid="@item.Id" asp-route-groupid="@ViewBag.groupid" asp-route-position="Translater">Promote to worker</a> |
                        <a asp-controller="Groups" asp-action="Promote" asp-route-userid="@item.Id" asp-route-groupid="@ViewBag.groupid" asp-route-position="Manager">Promote to manager</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    

    <a asp-controller="Groups"
       asp-action="UserSearch"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       asp-route-groupid="@ViewBag.groupid"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-controller="Groups"
       asp-action="UserSearch"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       asp-route-groupid="@ViewBag.groupid"
       class="btn btn-default @nextDisabled">
        Next
    </a>
}